export type Locale = "en" | "es";
export type Copy = Record<Locale, string>;

export const phone = "(707) 738-1746";
export const phoneHref = "tel:+17077381746";
export const email = "rosaleslandscaping707@gmail.com";
export const googleProfileUrl = "https://g.page/r/CRBWklLOWBW9EBM";
export const siteUrl = "https://rosaleslandscapingca.com";

// Production assets served from client/public/images (see scripts/fetch-assets.mjs
// to hydrate the real project photography into that folder).
export const assets = {
  logo: "/images/rosales-logo.png",
  logoDark: "/images/rosales-logo-dark.png",
  hero: "/images/paver-driveway-hero.webp",
  turf: "/images/synthetic-turf-garden.webp",
  stoneWall: "/images/granite-retaining-wall.webp",
  concrete: "/images/concrete-patio-process.webp",
  blockWall: "/images/block-retaining-wall.webp",
  flagstone: "/images/flagstone-patio.webp",
  kitchen: "/images/outdoor-kitchen-masonry.webp",
  deck: "/images/wood-deck-steps.webp",
  fence: "/images/wood-fence.webp",
  landscape: "/images/landscape-path-planting.webp",
  drainage: "/images/drainage-trench.webp",
  walkway: "/images/garden-walkway.webp",
  frontApproachBefore: "/images/front-approach-before.webp",
  frontApproachAfter: "/images/front-approach-after.webp",
};

export const copy = {
  en: {
    estimate: "Request an estimate", call: "Call (707) 738-1746", explore: "Explore our work", chat: "Ask our project assistant",
    home: "Home", services: "Services", projects: "Projects", about: "About", areas: "Areas", reviews: "Reviews", contact: "Contact",
    navLabel: "Primary navigation", language: "Language", menu: "Menu", close: "Close", more: "View service", back: "All services",
    license: "California C-27 License #1093687", serviceArea: "Napa · Vallejo · North Bay · 60-mile service radius", residential: "Residential & commercial",
    formTitle: "Tell us about your project", formText: "Share a few details and our team will follow up about your estimate.",
    fullName: "Full name", phone: "Phone", email: "Email", address: "Project address", city: "City", service: "Service", timeline: "When would you like to start?", message: "Project details", consent: "I agree to receive text messages about this request. Message and data rates may apply.",
    submit: "Send estimate request", sending: "Sending your request…", successTitle: "Your request is on its way.", successText: "Thank you. We received your project details and will be in touch soon.", error: "We couldn’t send your request. Please call us at (707) 738-1746.", required: "Please provide a phone number or email address.",
    privacyNote: "By submitting, you agree that Rosales may contact you about this request. Review our privacy policy and terms of use.",
  },
  es: {
    estimate: "Solicitar estimado", call: "Llamar al (707) 738-1746", explore: "Ver proyectos", chat: "Hablar con el asistente", 
    home: "Inicio", services: "Servicios", projects: "Proyectos", about: "Nosotros", areas: "Áreas", reviews: "Reseñas", contact: "Contacto",
    navLabel: "Navegación principal", language: "Idioma", menu: "Menú", close: "Cerrar", more: "Ver servicio", back: "Todos los servicios",
    license: "Licencia C-27 de California #1093687", serviceArea: "Napa · Vallejo · North Bay · Radio de servicio de 60 millas", residential: "Residencial y comercial",
    formTitle: "Cuéntenos sobre su proyecto", formText: "Comparta algunos detalles y nuestro equipo le contactará acerca de su estimado.",
    fullName: "Nombre completo", phone: "Teléfono", email: "Correo electrónico", address: "Dirección del proyecto", city: "Ciudad", service: "Servicio", timeline: "¿Cuándo desea comenzar?", message: "Detalles del proyecto", consent: "Acepto recibir mensajes de texto sobre esta solicitud. Pueden aplicar tarifas de mensajes y datos.",
    submit: "Enviar solicitud de estimado", sending: "Enviando su solicitud…", successTitle: "Su solicitud fue enviada.", successText: "Gracias. Recibimos los detalles de su proyecto y le contactaremos pronto.", error: "No pudimos enviar su solicitud. Por favor llámenos al (707) 738-1746.", required: "Proporcione un teléfono o correo electrónico.",
    privacyNote: "Al enviar, acepta que Rosales le contacte acerca de esta solicitud. Consulte nuestra política de privacidad y términos de uso.",
  },
} as const;

export type Service = { slug: string; name: Copy; eyebrow: Copy; title: Copy; summary: Copy; details: Copy; bullets: Record<Locale, string[]>; image: string; alt: Copy };

export const services: Service[] = [
  { slug: "landscaping", name: { en: "Landscaping", es: "Paisajismo" }, eyebrow: { en: "Landscape design & installation", es: "Diseño e instalación de paisajismo" }, title: { en: "Landscapes with a sense of place.", es: "Paisajes con sentido de lugar." }, summary: { en: "Thoughtful planting, grading, pathways, and outdoor composition for a property that feels complete.", es: "Plantación, nivelación, senderos y composición exterior pensados para que la propiedad se sienta completa." }, details: { en: "From a front approach to a backyard transformation, Rosales builds outdoor spaces that connect materials, planting, circulation, and everyday use.", es: "Desde una entrada frontal hasta la transformación de un patio, Rosales crea espacios exteriores que unen materiales, plantas, circulación y uso diario." }, bullets: { en: ["New landscape installation", "Planting and garden beds", "Walkways and outdoor transitions"], es: ["Instalación de paisajismo nuevo", "Plantación y jardines", "Senderos y transiciones exteriores"] }, image: assets.landscape, alt: { en: "Rosales landscape path and planting installation", es: "Sendero y plantación instalados por Rosales" } },
  { slug: "pavers", name: { en: "Pavers", es: "Adoquines" }, eyebrow: { en: "Patios, paths & driveways", es: "Patios, senderos y entradas" }, title: { en: "A more enduring surface underfoot.", es: "Una superficie más durable bajo sus pies." }, summary: { en: "Paver installations that bring structure, texture, and a finished sense of arrival to outdoor spaces.", es: "Instalaciones de adoquín que aportan estructura, textura y una llegada terminada a los espacios exteriores." }, details: { en: "Rosales approaches paver work as part of the whole site—preparation, drainage, transitions, and a surface made for everyday life.", es: "Rosales aborda los adoquines como parte de todo el terreno: preparación, drenaje, transiciones y una superficie hecha para la vida diaria." }, bullets: { en: ["Patios and entertaining areas", "Walkways and garden paths", "Paver driveways and entries"], es: ["Patios y áreas para convivir", "Senderos y caminos de jardín", "Entradas y accesos de adoquín"] }, image: assets.hero, alt: { en: "Rosales paver driveway and landscaped entry", es: "Entrada y camino de adoquín con paisajismo de Rosales" } },
  { slug: "concrete", name: { en: "Concrete", es: "Concreto" }, eyebrow: { en: "Form, finish & function", es: "Forma, acabado y función" }, title: { en: "Concrete work built on preparation.", es: "Concreto construido sobre una buena preparación." }, summary: { en: "Practical, polished concrete solutions for exterior living, movement, and structure.", es: "Soluciones prácticas y bien terminadas de concreto para espacios exteriores, circulación y estructura." }, details: { en: "A clean concrete result starts below the surface. Rosales plans the base, formwork, geometry, and finish around how the space will be used.", es: "Un buen resultado en concreto comienza debajo de la superficie. Rosales planifica la base, la cimbra, la geometría y el acabado según el uso del espacio." }, bullets: { en: ["Patios and pads", "Walkways and exterior steps", "Concrete preparation and formwork"], es: ["Patios y losas", "Senderos y escalones exteriores", "Preparación y cimbra de concreto"] }, image: assets.concrete, alt: { en: "Concrete patio construction by Rosales", es: "Construcción de patio de concreto por Rosales" } },
  { slug: "retaining-walls", name: { en: "Retaining Walls", es: "Muros de contención" }, eyebrow: { en: "Structure meets landscape", es: "Estructura y paisaje" }, title: { en: "Hold the land. Elevate the landscape.", es: "Sostenga el terreno. Eleve el paisaje." }, summary: { en: "Retaining walls that add support, define levels, and create a deliberate outdoor composition.", es: "Muros que aportan soporte, definen niveles y crean una composición exterior intencional." }, details: { en: "A retaining wall has to work before it can look effortless. Rosales brings careful material transitions and site-minded construction to every wall.", es: "Un muro de contención debe funcionar antes de verse natural. Rosales aporta transiciones cuidadosas de materiales y construcción consciente del terreno." }, bullets: { en: ["Stone and block walls", "Grade transitions", "Integrated paths and planting"], es: ["Muros de piedra y bloque", "Transiciones de nivel", "Senderos y plantación integrados"] }, image: assets.stoneWall, alt: { en: "Natural stone retaining wall completed by Rosales", es: "Muro de contención de piedra natural terminado por Rosales" } },
  { slug: "synthetic-turf", name: { en: "Synthetic Turf", es: "Césped sintético" }, eyebrow: { en: "Low-maintenance green space", es: "Espacio verde de bajo mantenimiento" }, title: { en: "Green, composed, and ready to use.", es: "Verde, bien compuesto y listo para usar." }, summary: { en: "Synthetic turf installations that make room for play, calm, and low-maintenance outdoor living.", es: "Instalaciones de césped sintético que crean espacio para jugar, descansar y vivir al aire libre con poco mantenimiento." }, details: { en: "Rosales coordinates turf with pavers, planting edges, drainage, and the real way your family uses the yard.", es: "Rosales coordina el césped con adoquines, bordes de plantación, drenaje y la forma real en que su familia usa el patio." }, bullets: { en: ["Backyards and side yards", "Putting greens and play areas", "Paver and turf transitions"], es: ["Patios traseros y laterales", "Putting greens y áreas de juego", "Transiciones entre adoquín y césped"] }, image: assets.turf, alt: { en: "Synthetic turf and stepping-stone garden installed by Rosales", es: "Césped sintético y sendero de losas instalados por Rosales" } },
  { slug: "fences-gates", name: { en: "Fences & Gates", es: "Cercas y portones" }, eyebrow: { en: "Privacy & definition", es: "Privacidad y definición" }, title: { en: "Boundaries made with care.", es: "Límites construidos con cuidado." }, summary: { en: "Fences and gates that bring privacy, structure, and a clean finish to the property edge.", es: "Cercas y portones que aportan privacidad, estructura y un acabado limpio al límite de la propiedad." }, details: { en: "A fence should complement the landscape around it. Rosales builds clear, durable boundaries with thoughtful alignment and transitions.", es: "Una cerca debe complementar el paisaje que la rodea. Rosales construye límites claros y durables con alineación y transiciones bien pensadas." }, bullets: { en: ["Wood fences", "Gates and property access", "Landscape-integrated boundaries"], es: ["Cercas de madera", "Portones y accesos", "Límites integrados al paisajismo"] }, image: assets.fence, alt: { en: "Wood fence installation by Rosales", es: "Instalación de cerca de madera por Rosales" } },
  { slug: "drainage-irrigation", name: { en: "Drainage & Irrigation", es: "Drenaje y riego" }, eyebrow: { en: "Site systems that work", es: "Sistemas de terreno que funcionan" }, title: { en: "Protect the work beneath the surface.", es: "Proteja el trabajo debajo de la superficie." }, summary: { en: "Drainage and irrigation planning for landscapes that need to look good and perform over time.", es: "Planificación de drenaje y riego para paisajes que deben verse bien y funcionar con el tiempo." }, details: { en: "Water is part of every exterior project. Rosales evaluates drainage routes, irrigation needs, and the construction sequence before final surfaces go in.", es: "El agua es parte de todo proyecto exterior. Rosales evalúa rutas de drenaje, necesidades de riego y la secuencia de construcción antes de instalar las superficies finales." }, bullets: { en: ["Drainage trenching and routing", "Irrigation service and repair", "Grade-aware outdoor preparation"], es: ["Zanjas y rutas de drenaje", "Servicio y reparación de riego", "Preparación exterior consciente de niveles"] }, image: assets.drainage, alt: { en: "Drainage trench preparation by Rosales", es: "Preparación de zanja de drenaje por Rosales" } },
  { slug: "decks", name: { en: "Decks", es: "Decks" }, eyebrow: { en: "Outdoor levels & entries", es: "Niveles y accesos exteriores" }, title: { en: "A stronger connection to outside.", es: "Una conexión más sólida con el exterior." }, summary: { en: "Decks and steps that create a comfortable, well-finished transition from home to landscape.", es: "Decks y escalones que crean una transición cómoda y bien terminada entre la casa y el paisaje." }, details: { en: "Rosales builds deck and stair solutions that consider elevation, access, material warmth, and how the surrounding landscape comes together.", es: "Rosales construye soluciones de decks y escaleras que consideran altura, acceso, calidez de materiales y cómo se integra el paisaje alrededor." }, bullets: { en: ["Exterior deck surfaces", "Entry stairs and landings", "Landscape-facing transitions"], es: ["Superficies de deck exterior", "Escaleras y descansos de acceso", "Transiciones hacia el paisaje"] }, image: assets.deck, alt: { en: "Wood deck and entry steps installed by Rosales", es: "Deck de madera y escalones de acceso instalados por Rosales" } },
  { slug: "stonework", name: { en: "Stonework", es: "Trabajo en piedra" }, eyebrow: { en: "Texture, detail & permanence", es: "Textura, detalle y permanencia" }, title: { en: "Material character, carefully placed.", es: "Carácter del material, cuidadosamente colocado." }, summary: { en: "Stone patios, paths, walls, and outdoor features built to feel native to the setting.", es: "Patios, senderos, muros y elementos exteriores de piedra creados para sentirse naturales en el entorno." }, details: { en: "Stonework brings a tactile sense of permanence. Rosales composes materials, edges, and levels into spaces made to be lived in.", es: "El trabajo en piedra aporta una sensación táctil de permanencia. Rosales compone materiales, bordes y niveles en espacios hechos para disfrutarse." }, bullets: { en: ["Flagstone patios", "Masonry details", "Stone paths and outdoor features"], es: ["Patios de flagstone", "Detalles de mampostería", "Senderos de piedra y elementos exteriores"] }, image: assets.flagstone, alt: { en: "Flagstone patio project by Rosales", es: "Proyecto de patio de flagstone por Rosales" } },
  { slug: "driveways", name: { en: "Driveways", es: "Entradas" }, eyebrow: { en: "Arrival, access & curb appeal", es: "Llegada, acceso y atractivo exterior" }, title: { en: "Make the first impression durable.", es: "Haga durable la primera impresión." }, summary: { en: "Driveways and front approaches designed for daily use and a more considered arrival.", es: "Entradas y accesos frontales diseñados para uso diario y una llegada más cuidada." }, details: { en: "A driveway is a working surface and the first view of a property. Rosales brings material coordination and clean geometry to both.", es: "Una entrada es una superficie de uso diario y la primera vista de una propiedad. Rosales aporta coordinación de materiales y geometría limpia a ambas." }, bullets: { en: ["Paver driveways", "Front paths and approaches", "Hardscape and landscape coordination"], es: ["Entradas de adoquín", "Senderos y accesos frontales", "Coordinación de hardscape y paisaje"] }, image: assets.walkway, alt: { en: "Rosales front garden walkway installation", es: "Instalación de sendero frontal por Rosales" } },
];

export const navItems = [
  { href: "/", key: "home" }, { href: "/services/", key: "services" }, { href: "/projects/", key: "projects" }, { href: "/about/", key: "about" }, { href: "/areas-we-serve/", key: "areas" }, { href: "/contact/", key: "contact" },
] as const;

export const socialLinks = [
  { label: "Google", href: googleProfileUrl },
  { label: "Facebook", href: "https://www.facebook.com/people/Rosales-Landscaping-Construction-Inc/61551280705514/" },
  { label: "Instagram", href: "https://www.instagram.com/rosaleslandscaping_inc/" },
  { label: "Yelp", href: "https://www.yelp.com.mx/biz/rosales-landscaping-napa" },
  { label: "Houzz", href: "https://www.houzz.com/hznb/projects/news-pj-vj~7155969" },
  { label: "TikTok", href: "https://www.tiktok.com/@rosales.landscapi" },
];
