import { ArrowRight, Phone } from "lucide-react";
import { Link } from "wouter";
import { EstimateForm } from "@/components/EstimateForm";
import { Seo } from "@/components/Seo";
import { ServiceIndex } from "@/components/ServiceIndex";
import { ProjectTransformation } from "@/components/ProjectTransformation";
import { BuildTimeline } from "@/components/BuildTimeline";
import { assets, copy, phoneHref } from "@/lib/site-content";
import { useLocale } from "@/contexts/LocaleContext";

export default function Home() {
  const { locale } = useLocale();
  const t = copy[locale];
  const english = locale === "en";
  return <><Seo title={english ? "Landscaping & outdoor construction" : "Paisajismo y construcción exterior"} description={english ? "Rosales creates considered landscapes, pavers, concrete, retaining walls, turf, fences, drainage, decks, stonework, and driveways across the North Bay." : "Rosales crea paisajismo, adoquines, concreto, muros de contención, césped, cercas, drenaje, decks, piedra y entradas en North Bay."} path="/" image={assets.hero} schema={{ "@context": "https://schema.org", "@type": "HomeAndConstructionBusiness", name: "Rosales Landscaping & Construction Inc", url: "https://rosaleslandscapingandconstruction.com", telephone: "+17077381746", email: "rosaleslandscaping707@gmail.com", areaServed: ["Napa", "Vallejo", "Fairfield", "Concord", "Richmond", "Benicia"], sameAs: ["https://www.instagram.com/rosaleslandscaping_inc/", "https://www.facebook.com/people/Rosales-Landscaping-Construction-Inc/61551280705514/"], hasCredential: "California C-27 License #1093687" }} />
    <section className="home-hero"><img className="hero-photo" src={assets.hero} alt={english ? "Rosales paver driveway and landscaped entry" : "Entrada y camino de adoquín con paisajismo de Rosales"} fetchPriority="high" decoding="async" /><div className="hero-shade" /><div className="container hero-content"><div className="hero-kicker"><span>{t.license}</span><i /> <span>{t.residential}</span></div><h1>{english ? <>Landscapes made<br />to <em>hold their place.</em></> : <>Paisajes hechos<br />para <em>perdurar.</em></>}</h1><p>{english ? "Precision-built outdoor spaces across Napa, Vallejo, and the North Bay." : "Espacios exteriores construidos con precisión en Napa, Vallejo y North Bay."}</p><div className="hero-actions"><a className="button button-primary" href="#estimate">{t.estimate}<ArrowRight size={17} /></a><Link className="button button-ghost" href="/projects/">{t.explore}</Link></div></div><div className="hero-scroll"><span>{english ? "Scroll to explore" : "Deslice para explorar"}</span><i /></div></section>
    <section className="section intro-section"><div className="container two-column"><div><span className="eyebrow">{english ? "Rosales Landscaping & Construction" : "Rosales Landscaping & Construction"}</span><h2>{english ? <>More than a yard.<br />A <em>finished feeling.</em></> : <>Más que un patio.<br />Una <em>sensación terminada.</em></>}</h2></div><div><p className="large-copy">{english ? "We bring landscaping and construction together with a sharp eye for materials, movement, structure, and the everyday moments a property needs to support." : "Unimos paisajismo y construcción con una mirada precisa para los materiales, la circulación, la estructura y los momentos diarios que una propiedad necesita sostener."}</p><div className="service-radius"><span>{english ? "60-mile service radius" : "Radio de servicio de 60 millas"}</span><strong>{english ? "Based in Vallejo · serving Napa, the North Bay, and surrounding communities" : "Con base en Vallejo · atendiendo Napa, North Bay y comunidades cercanas"}</strong></div><Link href="/about/" className="text-link">{english ? "Meet Rosales" : "Conozca a Rosales"}<ArrowRight size={16} /></Link></div></div></section>
    <ProjectTransformation />
    <section className="section dark-section service-feature"><div className="container"><div className="section-heading inverted"><div><span className="eyebrow">{english ? "The work" : "El trabajo"}</span><h2>{english ? "Built around the way you live outside." : "Construido alrededor de su vida exterior."}</h2></div><Link href="/services/" className="text-link">{english ? "View all services" : "Ver todos los servicios"}<ArrowRight size={16} /></Link></div><ServiceIndex featured={["pavers", "retaining-walls", "concrete", "synthetic-turf"]} /></div></section>
    <section className="section project-feature"><div className="container"><div className="project-feature-grid"><div className="project-feature-image"><img src={assets.kitchen} alt={english ? "Rosales outdoor kitchen and masonry project" : "Proyecto de cocina exterior y mampostería de Rosales"} loading="lazy" /></div><div className="project-feature-copy"><span className="eyebrow">{english ? "A portfolio of real work" : "Un portafolio de trabajo real"}</span><h2>{english ? "From the ground up, every detail has a job to do." : "Desde el suelo, cada detalle tiene una función."}</h2><p>{english ? "Explore a selection of outdoor projects shaped through hardscape, planting, stone, wood, and well-considered transitions." : "Explore una selección de proyectos exteriores creados mediante hardscape, plantación, piedra, madera y transiciones bien pensadas."}</p><Link href="/projects/" className="button button-dark">{t.explore}<ArrowRight size={17} /></Link></div></div></div></section>
    <BuildTimeline />
    <section className="section estimate-section" id="estimate"><div className="container estimate-layout"><div className="estimate-intro"><span className="eyebrow">{english ? "Start your project" : "Comience su proyecto"}</span><h2>{english ? "Let’s make room for what comes next." : "Hagamos espacio para lo que sigue."}</h2><p>{english ? "Tell us what you are planning. A thoughtful outdoor project begins with a thoughtful first conversation." : "Cuéntenos lo que está planeando. Un proyecto exterior pensado comienza con una primera conversación bien hecha."}</p><a className="call-line" href={phoneHref}><Phone size={18} />{t.call}</a></div><EstimateForm /></div></section>
    <section className="chat-nudge"><div><span>{english ? "Have a question before you begin?" : "¿Tiene una pregunta antes de comenzar?"}</span><strong>{english ? "Chat with our project assistant." : "Hable con nuestro asistente de proyectos."}</strong></div><button onClick={() => { const button = document.getElementById("lp-widget-btn"); if (button) button.click(); else window.dispatchEvent(new Event("leadprime:unavailable")); }}>{t.chat}<ArrowRight size={16} /></button></section>
  </>;
}
